name = "ArbitrageFreeSABR"
uuid = "2608ead3-6571-486a-ad88-5e77169cf741"
authors = ["fabien_lefloch <fabien_lefloch@calypso.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
